/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-2",
    "aws_cognito_identity_pool_id": "us-east-2:68caac8f-6d71-4ca4-9784-027fa5b3fbcb",
    "aws_cognito_region": "us-east-2",
    "aws_user_pools_id": "us-east-2_I0o3RhNeL",
    "aws_user_pools_web_client_id": "1toqk99b31koe6jtdrgsker3cg",
    "oauth": {
        "domain": "cribfoxformui275015b8-275015b8-dev.auth.us-east-2.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "http://localhost:3000/",
        "redirectSignOut": "http://localhost:3000/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_appsync_graphqlEndpoint": "https://pwlz2vtxzbad3ddinz76ypptoa.appsync-api.us-east-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-2",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-wmsnf4kiajczxbuqx5uzrcpjma"
};


export default awsmobile;
